<?php

function create_commune_schema($prefix, $dbprefix, $collate, $tablename) {
    $tableName = $prefix.$dbprefix.$tablename;

    $sql = "CREATE TABLE IF NOT EXISTS {$tableName} (
        id_commune int(11) NOT NULL AUTO_INCREMENT,
        id_province int(11) NOT NULL,
        name varchar(100) NOT NULL,
        actived TINYINT(1) DEFAULT 1,
        PRIMARY KEY (id_commune)
    ) COLLATE $collate";

    return array(
        'schema' => $sql,
        'data' => populate_commune_schema(),
        'tablename' => $tableName
    );
}

function populate_commune_schema() {
    $sql = array(
        array('name' => 'Arica', 'id_province' => 1),
        array('name' => 'Camarones', 'id_province' => 1),
        array('name' => 'General Lagos', 'id_province' => 2),
        array('name' => 'Putre', 'id_province' => 2),
        array('name' => 'Alto Hospicio', 'id_province' => 3),
        array('name' => 'Iquique', 'id_province' => 3),
        array('name' => 'Camiña', 'id_province' => 4),
        array('name' => 'Colchane', 'id_province' => 4),
        array('name' => 'Huara', 'id_province' => 4),
        array('name' => 'Pica', 'id_province' => 4),
        array('name' => 'Pozo Almonte', 'id_province' => 4),
        array('name' => 'Antofagasta', 'id_province' => 5),
        array('name' => 'Mejillones', 'id_province' => 5),
        array('name' => 'Sierra Gorda', 'id_province' => 5),
        array('name' => 'Taltal', 'id_province' => 5),
        array('name' => 'Calama', 'id_province' => 6),
        array('name' => 'Ollague', 'id_province' => 6),
        array('name' => 'San Pedro de Atacama', 'id_province' => 6),
        array('name' => 'María Elena', 'id_province' => 7),
        array('name' => 'Tocopilla', 'id_province' => 7),
        array('name' => 'Chañaral', 'id_province' => 8),
        array('name' => 'Diego de Almagro', 'id_province' => 8),
        array('name' => 'Caldera', 'id_province' => 9),
        array('name' => 'Copiapó', 'id_province' => 9),
        array('name' => 'Tierra Amarilla', 'id_province' => 9),
        array('name' => 'Alto del Carmen', 'id_province' => 10),
        array('name' => 'Freirina', 'id_province' => 10),
        array('name' => 'Huasco', 'id_province' => 10),
        array('name' => 'Vallenar', 'id_province' => 10),
        array('name' => 'Canela', 'id_province' => 11),
        array('name' => 'Illapel', 'id_province' => 11),
        array('name' => 'Los Vilos', 'id_province' => 11),
        array('name' => 'Salamanca', 'id_province' => 11),
        array('name' => 'Andacollo', 'id_province' => 12),
        array('name' => 'Coquimbo', 'id_province' => 12),
        array('name' => 'La Higuera', 'id_province' => 12),
        array('name' => 'La Serena', 'id_province' => 12),
        array('name' => 'Paihuaco', 'id_province' => 12),
        array('name' => 'Vicuña', 'id_province' => 12),
        array('name' => 'Combarbalá', 'id_province' => 13),
        array('name' => 'Monte Patria', 'id_province' => 13),
        array('name' => 'Ovalle', 'id_province' => 13),
        array('name' => 'Punitaqui', 'id_province' => 13),
        array('name' => 'Río Hurtado', 'id_province' => 13),
        array('name' => 'Isla de Pascua', 'id_province' => 14),
        array('name' => 'Calle Larga', 'id_province' => 15),
        array('name' => 'Los Andes', 'id_province' => 15),
        array('name' => 'Rinconada', 'id_province' => 15),
        array('name' => 'San Esteban', 'id_province' => 15),
        array('name' => 'La Ligua', 'id_province' => 16),
        array('name' => 'Papudo', 'id_province' => 16),
        array('name' => 'Petorca', 'id_province' => 16),
        array('name' => 'Zapallar', 'id_province' => 16),
        array('name' => 'Hijuelas', 'id_province' => 17),
        array('name' => 'La Calera', 'id_province' => 17),
        array('name' => 'La Cruz', 'id_province' => 17),
        array('name' => 'Limache', 'id_province' => 17),
        array('name' => 'Nogales', 'id_province' => 17),
        array('name' => 'Olmué', 'id_province' => 17),
        array('name' => 'Quillota', 'id_province' => 17),
        array('name' => 'Algarrobo', 'id_province' => 18),
        array('name' => 'Cartagena', 'id_province' => 18),
        array('name' => 'El Quisco', 'id_province' => 18),
        array('name' => 'El Tabo', 'id_province' => 18),
        array('name' => 'San Antonio', 'id_province' => 18),
        array('name' => 'Santo Domingo', 'id_province' => 18),
        array('name' => 'Catemu', 'id_province' => 19),
        array('name' => 'Llaillay', 'id_province' => 19),
        array('name' => 'Panquehue', 'id_province' => 19),
        array('name' => 'Putaendo', 'id_province' => 19),
        array('name' => 'San Felipe', 'id_province' => 19),
        array('name' => 'Santa María', 'id_province' => 19),
        array('name' => 'Casablanca', 'id_province' => 20),
        array('name' => 'Concón', 'id_province' => 20),
        array('name' => 'Juan Fernández', 'id_province' => 20),
        array('name' => 'Puchuncaví', 'id_province' => 20),
        array('name' => 'Quilpué', 'id_province' => 20),
        array('name' => 'Quintero', 'id_province' => 20),
        array('name' => 'Valparaíso', 'id_province' => 20),
        array('name' => 'Villa Alemana', 'id_province' => 20),
        array('name' => 'Viña del Mar', 'id_province' => 20),
        array('name' => 'Colina', 'id_province' => 21),
        array('name' => 'Lampa', 'id_province' => 21),
        array('name' => 'Tiltil', 'id_province' => 21),
        array('name' => 'Pirque', 'id_province' => 22),
        array('name' => 'Puente Alto', 'id_province' => 22),
        array('name' => 'San José de Maipo', 'id_province' => 22),
        array('name' => 'Buin', 'id_province' => 23),
        array('name' => 'Calera de Tango', 'id_province' => 23),
        array('name' => 'Paine', 'id_province' => 23),
        array('name' => 'San Bernardo', 'id_province' => 23),
        array('name' => 'Alhué', 'id_province' => 24),
        array('name' => 'Curacaví', 'id_province' => 24),
        array('name' => 'María Pinto', 'id_province' => 24),
        array('name' => 'Melipilla', 'id_province' => 24),
        array('name' => 'San Pedro', 'id_province' => 24),
        array('name' => 'Cerrillos', 'id_province' => 25),
        array('name' => 'Cerro Navia', 'id_province' => 25),
        array('name' => 'Conchalí', 'id_province' => 25),
        array('name' => 'El Bosque', 'id_province' => 25),
        array('name' => 'Estación Central', 'id_province' => 25),
        array('name' => 'Huechuraba', 'id_province' => 25),
        array('name' => 'Independencia', 'id_province' => 25),
        array('name' => 'La Cisterna', 'id_province' => 25),
        array('name' => 'La Granja', 'id_province' => 25),
        array('name' => 'La Florida', 'id_province' => 25),
        array('name' => 'La Pintana', 'id_province' => 25),
        array('name' => 'La Reina', 'id_province' => 25),
        array('name' => 'Las Condes', 'id_province' => 25),
        array('name' => 'Lo Barnechea', 'id_province' => 25),
        array('name' => 'Lo Espejo', 'id_province' => 25),
        array('name' => 'Lo Prado', 'id_province' => 25),
        array('name' => 'Macul', 'id_province' => 25),
        array('name' => 'Maipú', 'id_province' => 25),
        array('name' => 'Ñuñoa', 'id_province' => 25),
        array('name' => 'Pedro Aguirre Cerda', 'id_province' => 25),
        array('name' => 'Peñalolén', 'id_province' => 25),
        array('name' => 'Providencia', 'id_province' => 25),
        array('name' => 'Pudahuel', 'id_province' => 25),
        array('name' => 'Quilicura', 'id_province' => 25),
        array('name' => 'Quinta Normal', 'id_province' => 25),
        array('name' => 'Recoleta', 'id_province' => 25),
        array('name' => 'Renca', 'id_province' => 25),
        array('name' => 'San Miguel', 'id_province' => 25),
        array('name' => 'San Joaquín', 'id_province' => 25),
        array('name' => 'San Ramón', 'id_province' => 25),
        array('name' => 'Santiago', 'id_province' => 25),
        array('name' => 'Vitacura', 'id_province' => 25),
        array('name' => 'El Monte', 'id_province' => 26),
        array('name' => 'Isla de Maipo', 'id_province' => 26),
        array('name' => 'Padre Hurtado', 'id_province' => 26),
        array('name' => 'Peñaflor', 'id_province' => 26),
        array('name' => 'Talagante', 'id_province' => 26),
        array('name' => 'Codegua', 'id_province' => 27),
        array('name' => 'Coínco', 'id_province' => 27),
        array('name' => 'Coltauco', 'id_province' => 27),
        array('name' => 'Doñihue', 'id_province' => 27),
        array('name' => 'Graneros', 'id_province' => 27),
        array('name' => 'Las Cabras', 'id_province' => 27),
        array('name' => 'Machalí', 'id_province' => 27),
        array('name' => 'Malloa', 'id_province' => 27),
        array('name' => 'Mostazal', 'id_province' => 27),
        array('name' => 'Olivar', 'id_province' => 27),
        array('name' => 'Peumo', 'id_province' => 27),
        array('name' => 'Pichidegua', 'id_province' => 27),
        array('name' => 'Quinta de Tilcoco', 'id_province' => 27),
        array('name' => 'Rancagua', 'id_province' => 27),
        array('name' => 'Rengo', 'id_province' => 27),
        array('name' => 'Requínoa', 'id_province' => 27),
        array('name' => 'San Vicente de Tagua Tagua', 'id_province' => 27),
        array('name' => 'La Estrella', 'id_province' => 28),
        array('name' => 'Litueche', 'id_province' => 28),
        array('name' => 'Marchihue', 'id_province' => 28),
        array('name' => 'Navidad', 'id_province' => 28),
        array('name' => 'Peredones', 'id_province' => 28),
        array('name' => 'Pichilemu', 'id_province' => 28),
        array('name' => 'Chépica', 'id_province' => 29),
        array('name' => 'Chimbarongo', 'id_province' => 29),
        array('name' => 'Lolol', 'id_province' => 29),
        array('name' => 'Nancagua', 'id_province' => 29),
        array('name' => 'Palmilla', 'id_province' => 29),
        array('name' => 'Peralillo', 'id_province' => 29),
        array('name' => 'Placilla', 'id_province' => 29),
        array('name' => 'Pumanque', 'id_province' => 29),
        array('name' => 'San Fernando', 'id_province' => 29),
        array('name' => 'Santa Cruz', 'id_province' => 29),
        array('name' => 'Cauquenes', 'id_province' => 30),
        array('name' => 'Chanco', 'id_province' => 30),
        array('name' => 'Pelluhue', 'id_province' => 30),
        array('name' => 'Curicó', 'id_province' => 31),
        array('name' => 'Hualañé', 'id_province' => 31),
        array('name' => 'Licantén', 'id_province' => 31),
        array('name' => 'Molina', 'id_province' => 31),
        array('name' => 'Rauco', 'id_province' => 31),
        array('name' => 'Romeral', 'id_province' => 31),
        array('name' => 'Sagrada Familia', 'id_province' => 31),
        array('name' => 'Teno', 'id_province' => 31),
        array('name' => 'Vichuquén', 'id_province' => 31),
        array('name' => 'Colbún', 'id_province' => 32),
        array('name' => 'Linares', 'id_province' => 32),
        array('name' => 'Longaví', 'id_province' => 32),
        array('name' => 'Parral', 'id_province' => 32),
        array('name' => 'Retiro', 'id_province' => 32),
        array('name' => 'San Javier', 'id_province' => 32),
        array('name' => 'Villa Alegre', 'id_province' => 32),
        array('name' => 'Yerbas Buenas', 'id_province' => 32),
        array('name' => 'Constitución', 'id_province' => 33),
        array('name' => 'Curepto', 'id_province' => 33),
        array('name' => 'Empedrado', 'id_province' => 33),
        array('name' => 'Maule', 'id_province' => 33),
        array('name' => 'Pelarco', 'id_province' => 33),
        array('name' => 'Pencahue', 'id_province' => 33),
        array('name' => 'Río Claro', 'id_province' => 33),
        array('name' => 'San Clemente', 'id_province' => 33),
        array('name' => 'San Rafael', 'id_province' => 33),
        array('name' => 'Talca', 'id_province' => 33),
        array('name' => 'Arauco', 'id_province' => 34),
        array('name' => 'Cañete', 'id_province' => 34),
        array('name' => 'Contulmo', 'id_province' => 34),
        array('name' => 'Curanilahue', 'id_province' => 34),
        array('name' => 'Lebu', 'id_province' => 34),
        array('name' => 'Los Álamos', 'id_province' => 34),
        array('name' => 'Tirúa', 'id_province' => 34),
        array('name' => 'Alto Biobío', 'id_province' => 35),
        array('name' => 'Antuco', 'id_province' => 35),
        array('name' => 'Cabrero', 'id_province' => 35),
        array('name' => 'Laja', 'id_province' => 35),
        array('name' => 'Los Ángeles', 'id_province' => 35),
        array('name' => 'Mulchén', 'id_province' => 35),
        array('name' => 'Nacimiento', 'id_province' => 35),
        array('name' => 'Negrete', 'id_province' => 35),
        array('name' => 'Quilaco', 'id_province' => 35),
        array('name' => 'Quilleco', 'id_province' => 35),
        array('name' => 'San Rosendo', 'id_province' => 35),
        array('name' => 'Santa Bárbara', 'id_province' => 35),
        array('name' => 'Tucapel', 'id_province' => 35),
        array('name' => 'Yumbel', 'id_province' => 35),
        array('name' => 'Chiguayante', 'id_province' => 36),
        array('name' => 'Concepción', 'id_province' => 36),
        array('name' => 'Coronel', 'id_province' => 36),
        array('name' => 'Florida', 'id_province' => 36),
        array('name' => 'Hualpén', 'id_province' => 36),
        array('name' => 'Hualqui', 'id_province' => 36),
        array('name' => 'Lota', 'id_province' => 36),
        array('name' => 'Penco', 'id_province' => 36),
        array('name' => 'San Pedro de La Paz', 'id_province' => 36),
        array('name' => 'Santa Juana', 'id_province' => 36),
        array('name' => 'Talcahuano', 'id_province' => 36),
        array('name' => 'Tomé', 'id_province' => 36),
        array('name' => 'Bulnes', 'id_province' => 37),
        array('name' => 'Chillán', 'id_province' => 37),
        array('name' => 'Chillán Viejo', 'id_province' => 37),
        array('name' => 'Cobquecura', 'id_province' => 37),
        array('name' => 'Coelemu', 'id_province' => 37),
        array('name' => 'Coihueco', 'id_province' => 37),
        array('name' => 'El Carmen', 'id_province' => 37),
        array('name' => 'Ninhue', 'id_province' => 37),
        array('name' => 'Ñiquen', 'id_province' => 37),
        array('name' => 'Pemuco', 'id_province' => 37),
        array('name' => 'Pinto', 'id_province' => 37),
        array('name' => 'Portezuelo', 'id_province' => 37),
        array('name' => 'Quillón', 'id_province' => 37),
        array('name' => 'Quirihue', 'id_province' => 37),
        array('name' => 'Ránquil', 'id_province' => 37),
        array('name' => 'San Carlos', 'id_province' => 37),
        array('name' => 'San Fabián', 'id_province' => 37),
        array('name' => 'San Ignacio', 'id_province' => 37),
        array('name' => 'San Nicolás', 'id_province' => 37),
        array('name' => 'Treguaco', 'id_province' => 37),
        array('name' => 'Yungay', 'id_province' => 37),
        array('name' => 'Carahue', 'id_province' => 38),
        array('name' => 'Cholchol', 'id_province' => 38),
        array('name' => 'Cunco', 'id_province' => 38),
        array('name' => 'Curarrehue', 'id_province' => 38),
        array('name' => 'Freire', 'id_province' => 38),
        array('name' => 'Galvarino', 'id_province' => 38),
        array('name' => 'Gorbea', 'id_province' => 38),
        array('name' => 'Lautaro', 'id_province' => 38),
        array('name' => 'Loncoche', 'id_province' => 38),
        array('name' => 'Melipeuco', 'id_province' => 38),
        array('name' => 'Nueva Imperial', 'id_province' => 38),
        array('name' => 'Padre Las Casas', 'id_province' => 38),
        array('name' => 'Perquenco', 'id_province' => 38),
        array('name' => 'Pitrufquén', 'id_province' => 38),
        array('name' => 'Pucón', 'id_province' => 38),
        array('name' => 'Saavedra', 'id_province' => 38),
        array('name' => 'Temuco', 'id_province' => 38),
        array('name' => 'Teodoro Schmidt', 'id_province' => 38),
        array('name' => 'Toltén', 'id_province' => 38),
        array('name' => 'Vilcún', 'id_province' => 38),
        array('name' => 'Villarrica', 'id_province' => 38),
        array('name' => 'Angol', 'id_province' => 39),
        array('name' => 'Collipulli', 'id_province' => 39),
        array('name' => 'Curacautín', 'id_province' => 39),
        array('name' => 'Ercilla', 'id_province' => 39),
        array('name' => 'Lonquimay', 'id_province' => 39),
        array('name' => 'Los Sauces', 'id_province' => 39),
        array('name' => 'Lumaco', 'id_province' => 39),
        array('name' => 'Purén', 'id_province' => 39),
        array('name' => 'Renaico', 'id_province' => 39),
        array('name' => 'Traiguén', 'id_province' => 39),
        array('name' => 'Victoria', 'id_province' => 39),
        array('name' => 'Corral', 'id_province' => 40),
        array('name' => 'Lanco', 'id_province' => 40),
        array('name' => 'Los Lagos', 'id_province' => 40),
        array('name' => 'Máfil', 'id_province' => 40),
        array('name' => 'Mariquina', 'id_province' => 40),
        array('name' => 'Paillaco', 'id_province' => 40),
        array('name' => 'Panguipulli', 'id_province' => 40),
        array('name' => 'Valdivia', 'id_province' => 40),
        array('name' => 'Futrono', 'id_province' => 41),
        array('name' => 'La Unión', 'id_province' => 41),
        array('name' => 'Lago Ranco', 'id_province' => 41),
        array('name' => 'Río Bueno', 'id_province' => 41),
        array('name' => 'Ancud', 'id_province' => 42),
        array('name' => 'Castro', 'id_province' => 42),
        array('name' => 'Chonchi', 'id_province' => 42),
        array('name' => 'Curaco de Vélez', 'id_province' => 42),
        array('name' => 'Dalcahue', 'id_province' => 42),
        array('name' => 'Puqueldón', 'id_province' => 42),
        array('name' => 'Queilén', 'id_province' => 42),
        array('name' => 'Quemchi', 'id_province' => 42),
        array('name' => 'Quellón', 'id_province' => 42),
        array('name' => 'Quinchao', 'id_province' => 42),
        array('name' => 'Calbuco', 'id_province' => 43),
        array('name' => 'Cochamó', 'id_province' => 43),
        array('name' => 'Fresia', 'id_province' => 43),
        array('name' => 'Frutillar', 'id_province' => 43),
        array('name' => 'Llanquihue', 'id_province' => 43),
        array('name' => 'Los Muermos', 'id_province' => 43),
        array('name' => 'Maullín', 'id_province' => 43),
        array('name' => 'Puerto Montt', 'id_province' => 43),
        array('name' => 'Puerto Varas', 'id_province' => 43),
        array('name' => 'Osorno', 'id_province' => 44),
        array('name' => 'Puero Octay', 'id_province' => 44),
        array('name' => 'Purranque', 'id_province' => 44),
        array('name' => 'Puyehue', 'id_province' => 44),
        array('name' => 'Río Negro', 'id_province' => 44),
        array('name' => 'San Juan de la Costa', 'id_province' => 44),
        array('name' => 'San Pablo', 'id_province' => 44),
        array('name' => 'Chaitén', 'id_province' => 45),
        array('name' => 'Futaleufú', 'id_province' => 45),
        array('name' => 'Hualaihué', 'id_province' => 45),
        array('name' => 'Palena', 'id_province' => 45),
        array('name' => 'Aisén', 'id_province' => 46),
        array('name' => 'Cisnes', 'id_province' => 46),
        array('name' => 'Guaitecas', 'id_province' => 46),
        array('name' => 'Cochrane', 'id_province' => 47),
        array('name' => 'O\'higgins', 'id_province' => 47),
        array('name' => 'Tortel', 'id_province' => 47),
        array('name' => 'Coihaique', 'id_province' => 48),
        array('name' => 'Lago Verde', 'id_province' => 48),
        array('name' => 'Chile Chico', 'id_province' => 49),
        array('name' => 'Río Ibáñez', 'id_province' => 49),
        array('name' => 'Antártica', 'id_province' => 50),
        array('name' => 'Cabo de Hornos', 'id_province' => 50),
        array('name' => 'Laguna Blanca', 'id_province' => 51),
        array('name' => 'Punta Arenas', 'id_province' => 51),
        array('name' => 'Río Verde', 'id_province' => 51),
        array('name' => 'San Gregorio', 'id_province' => 51),
        array('name' => 'Porvenir', 'id_province' => 52),
        array('name' => 'Primavera', 'id_province' => 52),
        array('name' => 'Timaukel', 'id_province' => 52),
        array('name' => 'Natales', 'id_province' => 53),
        array('name' => 'Torres del Paine', 'id_province' => 53)
    );

    return $sql;
}